### ISSUE TITLE
Panic when printing a graph of a crate with path dependencies

### ISSUE THREAD

**Issue by sfackler** [sfackler/cargo-tree#1]
The Registry probably needs sources added for each path dependency but I'm not sure how it should all be hooked up.

**Comment by dtolnay** [comment]
This worked for me on serde_yaml_tests which has a [path dependency on serde_yaml](https://github.com/dtolnay/serde-yaml/blob/43d4588f4ead195f58a3aa4a9e83fe84a24c0557/yaml_tests/Cargo.toml#L17). If you remember which crate was causing trouble, I can try to tackle this.

**Comment by sfackler** [comment]
I can't seem to reproduce it either, but I seem to recall that I hit it in https://github.com/sfackler/rust-openssl. This might have been fixed in the last cargo update?

**Comment by dtolnay** [comment]
Okay let's call it fixed! I will follow up if I ever see it.

**Comment by sfackler** [comment]
Works for me!
