### ISSUE TITLE
Missing information with overridden dependencies

### ISSUE THREAD

**Issue by jethrogb** [sfackler/cargo-tree#10]
``` toml
[package]
name = "treetest"
version = "0.1.0"

[dependencies]
rand = "*"
```

results in:

```
$ cargo tree
treetest v0.1.0 (file:///tmp/treetest)
└── rand v0.3.14
    └── libc v0.2.14
```

but

``` toml
[package]
name = "treetest"
version = "0.1.0"

[dependencies]
rand = "*"

[replace]
'libc:0.2.14' = { git = "https://github.com/rust-lang/libc", tag = "0.2.14" }
```

results in:

```
$ cargo tree
treetest v0.1.0 (file:///tmp/treetest)
└── rand v0.3.14
```

**Comment by sfackler** [comment]
@alexcrichton where does information about overrides live?

**Comment by alexcrichton** [comment]
@sfackler if you're using Cargo this all [lives in `Resolve`](https://github.com/rust-lang/cargo/blob/f1bbc08e4e3197de326ae94eb41f4064cc892e09/src/cargo/core/resolver/mod.rs#L76) and you can witness it [via various methods](https://github.com/rust-lang/cargo/blob/f1bbc08e4e3197de326ae94eb41f4064cc892e09/src/cargo/core/resolver/mod.rs#L140-L154). Is that what you're looking for?

**Comment by sfackler** [comment]
Yep, thanks

**Comment by jethrogb** [comment]
Thanks for the quick fix!
