### ISSUE TITLE
Why cargo 1.41 isn't ok?

### ISSUE THREAD

**Issue by sammyne** [sfackler/cargo-tree#101]
## Environment

- cargo 1.41.0-nightly (8280633db 2019-11-11)
- rustc 1.41.0-nightly (412f43ac5 2019-11-24)

## Problems

`cargo tree` report `Error: cargo tree requires cargo 1.41 or newer`.

Really appreciate if someone could help me figure out why~

**Comment by sfackler** [comment]
You are using a nightly that probably doesn't have the cargo feature this crate requires.

**Comment by sammyne** [comment]
Does that mean the version requirement reported is the stable version of cargo, right?
@sfackler

**Comment by sfackler** [comment]
Yes.

**Comment by sammyne** [comment]
> Yes.

Thanks a lot~ 😄
