### ISSUE TITLE
Can't install using cargo install

### ISSUE THREAD

**Issue by jethrogb** [sfackler/cargo-tree#11]
Since openssl-sys 0.9.0 has been released, cargo's dependency resolution mechanism is unable to automatically choose a single openssl-sys version for this crate, resulting in a failed build:
```
  native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once
```

When I clone manually and do:
```
cargo update -p curl:0.3.10 --precise 0.3.9
cargo update -p openssl-sys:0.9.0 --precise 0.7.17
```
everything builds fine.

**Comment by sfackler** [comment]
@alexcrichton Is the lockfile still ignored for published binary crates?

**Comment by alexcrichton** [comment]
@sfackler I thought that was fixed but presumably not if this is happening.

**Comment by sfackler** [comment]
Was the fix on the publish side or the build side? If it's publish side I can republish this crate with nightly which may fix it?

**Comment by alexcrichton** [comment]
tbh I have no idea, I just vaguely remember something related to this

**Comment by sfackler** [comment]
Cool, I will experiment a bit tonight.

**Comment by sfackler** [comment]
Looks like nightly Cargo still drops the lockfile when packaging.

**Comment by sfackler** [comment]
```
$ cargo clean
$ cargo +nightly package --no-verify
   Packaging cargo-tree v0.7.0 (file:///Volumes/git/rust/cargo-tree)
$ tar tf target/package/cargo-tree-0.7.0.crate
cargo-tree-0.7.0/.gitignore
cargo-tree-0.7.0/.travis.yml
cargo-tree-0.7.0/Cargo.toml
cargo-tree-0.7.0/LICENSE-APACHE
cargo-tree-0.7.0/LICENSE-MIT
cargo-tree-0.7.0/README.md
cargo-tree-0.7.0/src/format/mod.rs
cargo-tree-0.7.0/src/format/parse.rs
cargo-tree-0.7.0/src/main.rs
```

**Comment by sfackler** [comment]
Looks like upstream crates have worked themselves out - I can successfully compile this off of an updated lockfile.
