### ISSUE TITLE
Sort `cargo tree -d`

### ISSUE THREAD

**Issue by dtolnay** [sfackler/cargo-tree#13]
I have a crate that has transitive dependencies on both serde 0.9 and serde 0.8. I can run `cargo tree -d` to discover this.

But sometimes serde 0.8 is shown before 0.9, sometimes after. I don't care whether the order is decreasing by version number or increasing by version number or something else but it should be consistent so that I can sanely diff the output before/after making a change to my Cargo.toml.

**Comment by dtolnay** [comment]
Thanks! :beers:

**Comment by sfackler** [comment]
Released 0.10.1 with this!
