### ISSUE TITLE
Support crate sizes

### ISSUE THREAD

**Issue by sevagh** [sfackler/cargo-tree#14]
Hello,

Not sure how possible this is to implement but it would be cool if there was a flag to show the size of each crate - like the downloaded size from crates.io.

**Comment by sfackler** [comment]
I'm not sure how easy it'll be to track down that information. Why are you interested in the size of the source distribution?

**Comment by sevagh** [comment]
Seems like the `*.rlib` files in `target/deps` have some associated size info.

I'm interested because my own crate has a very long download, and I wanted to start cutting down on dependencies - and I wanted to tackle the largest dependencies first.

**Comment by sevagh** [comment]
I suppose this is no longer interesting. Thanks for the mini discussion anyway!
