### ISSUE TITLE
Broken because latest cargo 0.20.0+ creates bare crate index

### ISSUE THREAD

**Issue by Arnavion** [sfackler/cargo-tree#15]
`rustc 1.19.0-nightly (75b056812 2017-05-15)`

`cargo 0.20.0-nightly (13d92c64d 2017-05-12)`

`cargo-tree` compiled against `cargo 0.18.0`

---

```sh
$ cargo tree
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: An unknown error occurred

$ RUST_LOG=trace cargo tree

<snip>

TRACE:cargo::core::source: loading SourceId; registry https://github.com/rust-lang/crates.io-index
    Updating registry `https://github.com/rust-lang/crates.io-index`
TRACE:cargo::sources::registry::remote: [registry https://github.com/rust-lang/crates.io-index] updating to rev 335e8a73a2d33fd1999bd9fdcbf52dd21e696af8
DEBUG:cargo: exit_with_error; err=CliError { error: Some(Error { code: -8, klass: 6, message: "Cannot reset hard. This operation is not allowed against bare repositories." }), unknown: true, exit_code: 101 }
```

The local crate index is indeed a bare repo (due to https://github.com/rust-lang/cargo/commit/15cc376b90c1dcc54cc4959f2e621cb8fa6de6f6 ) but cargo-tree compiles against an older cargo (0.18.0), so tries to `git reset --hard` the crate index repo ([`repo.reset(&object, git2::ResetType::Hard, None)?;`](https://github.com/rust-lang/cargo/commit/15cc376b90c1dcc54cc4959f2e621cb8fa6de6f6#diff-b9bdf97db2d115c5c703a0dc7d7935a4L112)), which fails.

I don't know if this can be fixed by changing cargo-tree to use cargo 0.20.0 (ie will it then stop working against crate index created by older cargo that isn't bare?) but I figured I'd atleast document this here.

cc @alexcrichton

**Comment by alexcrichton** [comment]
I believe this error is caused by https://github.com/rust-lang/cargo/issues/4058, fixed in https://github.com/rust-lang/cargo/pull/4060

**Comment by Arnavion** [comment]
Cool, thanks. I'll close this then since `cargo-tree` doesn't need to change.
