### ISSUE TITLE
Consider using cargo_metadata instead of cargo crate

### ISSUE THREAD

**Issue by malbarbo** [sfackler/cargo-tree#20]
It take too long to compile cargo. An alternative is to use [cargo_metadata](https://crates.io/crates/cargo_metadata), which offers an api over the `cargo metadata` command.

**Comment by sfackler** [comment]
I'd love to do this, but the last time I looked into it, the metadata resolution info didn't include the dependency kinds, unfortunately.

**Comment by malbarbo** [comment]
It seems that dependency kinds are included https://docs.rs/cargo_metadata/0.3.0/cargo_metadata/enum.DependencyKind.html

**Comment by sfackler** [comment]
Not in the `Resolve`: https://docs.rs/cargo_metadata/0.3.0/cargo_metadata/struct.Resolve.html

**Comment by sfackler** [comment]
Oh wait, I think I'm being silly. The Resolve cross references into the package set!

**Comment by sfackler** [comment]
It does look like cargo-metadata is missing controls for `--all-features`, `--no-default-features`, and `--features` though.

EDIT: and `--frozen` and `--locked`.

**Comment by sfackler** [comment]
These are also blockers:

https://github.com/rust-lang/cargo/issues/4631
https://github.com/rust-lang/cargo/issues/4632
