### ISSUE TITLE
--tree option has trouble reading Cargo.toml

### ISSUE THREAD

**Issue by kornelski** [sfackler/cargo-tree#22]
> cargo list --tree
> Couldn't read section `dependencies`.

I get the same error for every non-trivial project. My guess is that some dependency somewhere doesn't have this section.

I even get errors on an empty project:

```sh
cargo new empty
cd empty/
cargo list --tree
```
> Your Cargo.toml is missing.

but `Cargo.toml` is present (and it does have an empty `[dependencies]` section).

----

cargo --version
cargo 0.24.0-nightly (859c2305b 2017-10-29)
cargo list --version
cargo-list version 0.1.2

**Comment by sfackler** [comment]
`cargo-list` is a separate project from `cargo-tree`.

**Comment by kornelski** [comment]
Haha, ok. It's hard to trace what has installed what :)

[and `cargo tree` works fine]
