### ISSUE TITLE
Build-deps of dev-deps are not listed in any view

### ISSUE THREAD

**Issue by bluss** [sfackler/cargo-tree#23]
Basically, imagine there is a crate built and it does not show up in either of `cargo tree`, `cargo tree -k dev` or `cargo tree -k build`, where does it come from? It's from one of the dependencies' build deps!

Finally found it in this "view":

```
cargo tree -p newtype_derive -k build
newtype_derive v0.1.6
└── rustc_version v0.1.7
    └── semver v0.1.20
```

I'm sorry that I'm slightly lazy, I've only tested with cargo tree 0.14. It didn't look like recent git history had fixed this.

What's expected? I would kind of expect it in -k dev. I think I already disagree a bit with the kind split, because regular dependencies are not shown in -k dev. I'd like to see a tree of all crates that are built for dev-compiles (so in "cargo test"). That includes all regular deps and dev-deps. Digressions... but that kind of explains the bug, doesn't it?

**Comment by sfackler** [comment]
Yeah, this is one thing I've never been happy with - the specified kind only applies to the root of the tree, and we show normal runtime dependencies for transitive dependencies still.

I'm kind of leaning towards just displaying all dependencies of all kinds for everything, and grouping the different kinds together.

**Comment by bluss** [comment]
Sounds good. On my wish list there would be two main trees of all dependencies, corresponding to what's needed at either build or test.

Everything needed for cargo build (so build + normal + the same for each dep), Everything needed for cargo test (build + normal + dev + (build + normal for each dep)) and so on.

An example of question to answer would be like the one in this issue -- why is it building rustc_version?
