### ISSUE TITLE
`cargo install cargo-tree` fails without cmake installed

### ISSUE THREAD

**Issue by U007D** [sfackler/cargo-tree#24]
Even though Compiling cmake v0.1.26 is in cargo-tree's dependency list and compiled successfully during the install, another dependency,  flate2 v0.2.20 later failed with:
```
error: failed to run custom build command for `libssh2-sys v0.2.6`
process didn't exit successfully: `/tmp/cargo-install.bLOWRTFgeCJ3/release/build/libssh2-sys-ff367fac3f63f989/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/brad/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.2.6/libssh2" "-DCRYPTO_BACKEND=OpenSSL" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=/tmp/cargo-install.bLOWRTFgeCJ3/release/build/libssh2-sys-e9547953ed5244f2/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?
```
Not sure if the `cargo-tree install's` listed cmake dependency should have prevented this, or if this is a `flate2` problem or a `libssh2-sys` problem, but I thought I'd at least document the issue.

`sudo apt-get install cmake` resolved the issue, but I expected cargo to build without "external" dependencies.

(I am on nightly-x86_64-unknown-linux-gnu updated - rustc 1.23.0-nightly (a35a3abcd 2017-11-10))

**Comment by sfackler** [comment]
As noted in the readme, cmake is required to build this crate.

**Comment by U007D** [comment]
oops, I missed that--sorry for the spam, then!
