### ISSUE TITLE
can't install on windows because of libssh2-sys

### ISSUE THREAD

**Issue by radix** [sfackler/cargo-tree#29]
I'm sure there's some way to install libssh2-sys on windows, but why does cargo tree need it anyway? it seems like a spurious dependency. is there a way to disable it?

```
error: failed to run custom build command for `libssh2-sys v0.2.6`
process didn't exit successfully: `C:\Users\radix\AppData\Local\Temp\cargo-install.FV5LTR5nFsKM\release\build\libssh2-sys-86a416940bda1db0\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\radix\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libssh2-sys-0.2.6\\libssh2" "-G" "Visual Studio 15 2017 Win64" "-DCRYPTO_BACKEND=WinCNG" "-DZLIB_INCLUDE_DIR=C:\\Users\\radix\\AppData\\Local\\Temp\\cargo-install.FV5LTR5nFsKM\\release\\build\\libz-sys-7f501f039badde83\\out/include" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\radix\\AppData\\Local\\Temp\\cargo-install.FV5LTR5nFsKM\\release\\build\\libssh2-sys-31d17d69d1151c6b\\out" "-DCMAKE_C_FLAGS= /nologo /MD" "-DCMAKE_C_FLAGS_RELEASE= /nologo /MD" "-DCMAKE_CXX_FLAGS= /nologo /MD" "-DCMAKE_CXX_FLAGS_RELEASE= /nologo /MD" "-DCMAKE_BUILD_TYPE=Release"
```

**Comment by sfackler** [comment]
It's required because cargo tree uses cargo which uses libgit2 which uses libssh2. You'll need to install cmake.

**Comment by rakhmanu** [comment]
Hi when i tried this i had faced with the problem like this Can anyone help?
Compiling exonum_libsodium-sys v0.0.14
error: failed to run custom build command for `exonum_libsodium-sys v0.0.14`
process didn't exit successfully: `C:\Users\Уля\OneDrive\hello_cargo\target\debug\build\exonum_libsodium-sys-440368f41d859672\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '
"powershell" "-Command" "([Net.ServicePointManager]::SecurityProtocol = \'Tls12\') -and ((New-Object System.Net.WebClient).DownloadFile(\"https://download.libsodium.org/libsodium/releases/libsodium-1.0.13-msvc.zip\", \"C:\\Users\\Уля\\OneDrive\\hello_cargo\\target\\debug\\build\\exonum_libsodium-sys-9f97a51b4550d7b8\\out/installed/libsodium-1.0.13-msvc.zip\"))"
