### ISSUE TITLE
Remove the 'dependencies' items

### ISSUE THREAD

**Issue by RazrFalcon** [sfackler/cargo-tree#31]
In the new version a new item was added: `[dependencies]`. Can it be removed somehow? At least by a flag.

**Comment by sfackler** [comment]
They're there to differentiate between normal dependencies, dev dependencies, and build dependencies. Would you want all of those mixed together?

**Comment by RazrFalcon** [comment]
Does dev/build dependencies are shown by default? I thought that only normal dependencies are shown.

Then a flag to show only normal dependencies will be fine. Or, only normal dependencies can be shown by default and other can be shown by the flag.

**Comment by sfackler** [comment]
All kinds of dependencies are shown by default.

**Comment by RazrFalcon** [comment]
>Then a flag to show only normal dependencies will be fine.

**Comment by bluss** [comment]
@RazrFalcon To clarify here, if you want to see only normal dependencies, does that mean just [dependencies], recursively, or does it mean, all crates needed for "cargo build".

My entry point into this has been that "cargo build" needs both _dependencies_ and _build-dependencies_, recursively, so both those classes are thus "default" or "required" dependencies.

IMO the categories I'd see as natural are

1. Crates compiled for the build script in the current package
2. crates compiled for "cargo build" in the current package
3. crates compiled for "cargo test" in the current package.

**Comment by RazrFalcon** [comment]
My only problem is that there is too much noise.

Like:
```
├── fern v0.5.2
│   [dependencies]
│   └── log v0.4.1
│       [dependencies]
│       └── cfg-if v0.1.2
```

AFAIR, previous versions of the `cargo-tree` doesn't had one.

Maybe it's better to mark `dev-`, `build-` deps in `()` after version?

**Comment by bluss** [comment]
This is just my idea, but maybe hide the `[dependencies]` headers and still show the others? Using a suffix sounds fine too.

**Comment by sfackler** [comment]
Yeah it seems fine to not display `[dependencies]`.

**Comment by gilescope** [comment]
+1 [dependencies] increases the size by a third, people assume they're dependencies, if we could just mention the exceptions that would be great. Maybe call out the dev dependencies as a postfix on the line - that way it uses less console rows?
