### ISSUE TITLE
Add virtual manifest support

### ISSUE THREAD

**Issue by bjgill** [sfackler/cargo-tree#41]
In a workspace with a virtual manifest (one with `[workspace]`, but not `[package]`), we get the following error message:

```
$ cargo tree
error: manifest path `<path>/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

I suspect it should be fairly straightforward to switch over to using https://crates.io/crates/cargo_metadata to get the set of dependencies and their relationships. Cargo-metadata is fully workspace-aware - we use it in [cargo-edit](https://crates.io/crates/cargo-edit) for this purpose

**Comment by sfackler** [comment]
What would the dependency graph of a virtual manifest be?

cargo-metadata doesn't include enough information for us to be able to use it: #20

**Comment by mimoo** [comment]
@sfackler it would be the result of running `cargo tree` on all the listed members.

**Comment by mlindner** [comment]
@sfackler Please re-open this. Cargo tree needs to support virtual manifests. It should iterate through all entries in the virtual manifest. Cargo.toml lists a list of subpackages and it should show the trees for all of them.
