### ISSUE TITLE
Support for cargo feature 'edition'?

### ISSUE THREAD

**Issue by glelk** [sfackler/cargo-tree#42]
cargo-tree fails to parse manifest with `cargo-features = ["edition"]`

**Comment by sfackler** [comment]
cargo-tree builds against the most recent stable cargo release, so it'll need to wait until that feature reaches stable.

**Comment by burrbull** [comment]
edition 2018 is already *beta*

**Comment by gnzlbg** [comment]
> cargo-tree builds against the most recent stable cargo release, so it'll need to wait until that feature reaches stable.

By using the most recent stable cargo release, `cargo tree` only works on stable projects. If it were to use the most recent nightly release, `cargo tree` would work on all nightly, beta, and stable projects. 

If I'm going to download cargo sources and re-compile cargo to install `cargo tree`, its kind of a shame that it then only works on stable projects. Maybe there could be a cargo feature to enable using a nightly version of cargo?

**Comment by nebkor** [comment]
I've submitted a PR, https://github.com/sfackler/cargo-tree/pull/52, which I believe solves this.
