### ISSUE TITLE
cannot cargo run

### ISSUE THREAD

**Issue by rakhmanu** [sfackler/cargo-tree#46]
Hi when i tried this i had faced with the problem like this Can anyone help?
Compiling exonum_libsodium-sys v0.0.14
error: failed to run custom build command for exonum_libsodium-sys v0.0.14
process didn't exit successfully: C:\Users\Уля\OneDrive\hello_cargo\target\debug\build\exonum_libsodium-sys-440368f41d859672\build-script-build (exit code: 101)
--- stderr
thread 'main' panicked at '
"powershell" "-Command" "([Net.ServicePointManager]::SecurityProtocol = 'Tls12') -and ((New-Object System.Net.WebClient).DownloadFile("https://download.libsodium.org/libsodium/releases/libsodium-1.0.13-msvc.zip\", "C:\Users\Уля\OneDrive\hello_cargo\target\debug\build\exonum_libsodium-sys-9f97a51b4550d7b8\out/installed/libsodium-1.0.13-msvc.zip"))"

**Comment by sfackler** [comment]
That looks like an issue building the exonum_libsodium-sys crate, which cargo-tree doesn't use. You should file an issue with the exonum project.
