### ISSUE TITLE
error: failed to parse manifest Caused by: editions are unstable

### ISSUE THREAD

**Issue by naturallymitchell** [sfackler/cargo-tree#56]
https://github.com/rust-lang/cargo/issues/6113

**Comment by sfackler** [comment]
You're using an out of date version of cargo tree.

**Comment by naturallymitchell** [comment]
haunted by ghosts of Christmas past..

could you have foreseen this?

**Comment by naturallymitchell** [comment]
(could you have builtin an error, "your version of cargo uses an unfamiliar feature, or your edition is newer than blah balh... you probably need to update this program"?)

**Comment by sfackler** [comment]
This error is produced inside of cargo itself. That feature would have to be added there.

**Comment by naturallymitchell** [comment]
thanks
