### ISSUE TITLE
Cannot install on stock macOS

### ISSUE THREAD

**Issue by lilyball** [sfackler/cargo-tree#57]
`cargo-tree` won't build on stock macOS due to a transitive dependency on `openssl-sys` which I believe comes from `cargo`. The issue is that macOS ships with a very old version of OpenSSL that `openssl-sys` does not support. I'm pretty sure this can be worked around with `brew install openssl` but I don't use Homebrew so that doesn't work for me.

A quick look at https://github.com/rust-lang/cargo/blob/master/Cargo.toml indicates that there's a `vendored-openssl` feature flag, it might be a good idea to opt into that feature flag when building `cargo-tree` on macOS (or at least to re-expose it so I can select it myself).

**Comment by sfackler** [comment]
Sure - seems reasonable to add a `vendored-openssl` Cargo feature here.

**Comment by dtolnay** [comment]
It should be possible to select Cargo's vendored-openssl feature without cargo-tree specifically re-exposing it:

```bash
cargo install cargo-tree --features cargo/vendored-openssl
```

**Comment by lilyball** [comment]
Huh, that's not documented very well.

Incidentally, I think `cargo`'s `openssl` feature actually isn't the source of this after all. It's marked `optional` and I was really confused as to why it was being picked up. It's not. It's the `git2` dependency, which by default includes openssl.

Incidentally, I don't see any way, as an end user, of being able to say "turn off default features for this dependency". `cargo install cargo-tree --no-default-features` is going to ensure `cargo-tree` itself doesn't have default features but I wouldn't expect that to turn off default features on its dependencies (though the documentation isn't explicit, so it certainly could - EDIT: it doesn't).

That said, `--features cargo/vendored-openssl` seems to work. I guess it turns on the feature for openssl overall even though the dependency is coming via `git2` instead of `cargo`. I bet I could write `--features openssl/vendored` instead if I wanted to.

**Comment by lilyball** [comment]
Ok so, short term: Update the README to specify that on macOS you can say `--features openssl/vendored`.

Long term: Figure out how to disable the default features on `git2`. I don't know if you can just re-declare the `git2` dependency with features disabled, or what. Ideally `cargo` would have a feature that disables default features on `git2`, but I'm not sure if there's actually a way to specify that. I wish you could just write something like `--features git2/-default` to turn off the `default` feature.
