### ISSUE TITLE
Undefined symbol "___isOSVersionAtLeast" when building on OSX 10.14

### ISSUE THREAD

**Issue by kkoning** [sfackler/cargo-tree#58]
`cargo install cargo-tree` fails to build, with that error.  There's a fix that worked for me at the bottom.

Cargo version:

```
$ cargo --version
cargo 1.34.0-nightly (5c6aa46e6 2019-02-22)
```

Initial Build Error

```
$ cargo install cargo-tree
    Updating crates.io index
  Installing cargo-tree v0.24.0
   Compiling serde v1.0.89
   [...snip...]
   Compiling cargo v0.33.0
   Compiling cargo-tree v0.24.0
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L"
  [... tons of objects explicitly listed here...]

rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-93dcb870eb2f89d4.rlib" "-framework" "Security" "-liconv" "-framework" "Security" "-framework" "CoreFoundation" "-lssl" "-lcrypto" "-framework" "Security" "-framework" "CoreFoundation" "-lz" "-framework" "CoreFoundation" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: Undefined symbols for architecture x86_64:
            "___isOSVersionAtLeast", referenced from:
                _darwinssl_connect_common in libcurl_sys-90e4bc5d19684572.rlib(darwinssl.o)
                _darwinssl_connect_step2 in libcurl_sys-90e4bc5d19684572.rlib(darwinssl.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: failed to compile `cargo-tree v0.24.0`, intermediate artifacts can be found at `/var/folders/v8/z79nbgzs4_vddyznhfkr7rq40000z8/T/cargo-installNn4bfg`

Caused by:
  Could not compile `cargo-tree`.

To learn more, run the command again with --verbose.
```

I can make this succeed by adding `"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/lib/darwin/libclang_rt.osx.a"` to the large list of objects passed to `cc`.  This approach from a [blog entry](https://jonnyzzz.com/blog/2018/06/13/link-error-3/) that came up when I did a google search for the error/symbol.  The object output is (though not named that yet) the `cargo-tree` binary, and the command works if I copy it to `~/.cargo/bin/`

**Comment by sfackler** [comment]
This seems like something to file on [rust-curl](https://github.com/alexcrichton/curl-rust).

**Comment by kkoning** [comment]
I'm not exactly sure how this is a rust-curl issue, please feel free to educate me.  However, for whatever reason, as of today this build error is no longer occurring--based on your comment I'll assume due to some upstream problem that was fixed..  I'll mark the issue as closed.

**Comment by sfackler** [comment]
It's a rust-curl issue because that symbol is referenced from inside the Curl C library.
