### ISSUE TITLE
Option to mark/exclusively show crates in the tree with multiple versions

### ISSUE THREAD

**Issue by birkenfeld** [sfackler/cargo-tree#6]
Multiple versions pulled into the tree are often a source of confusion, e.g. with the infamous "expected crate::Foo, found crate::Foo" messages. `cargo tree` is nice to identify these crates and possible solutions, but it can be a bit tedious to find the relevant crates in the output.

I could see two modes to help here:
- mark (and colorize) crates with multiple versions and/or sources, similar to the `(*)` for truncated deps
- add an option to _only_ show these crates and their position in the tree

Thoughts? I'll give the implementation a try when the goal is clear.

**Comment by sfackler** [comment]
Something like this just recently merged, actually! #4 

I haven't gotten around to publishing a new release though - will do now.

**Comment by birkenfeld** [comment]
Nice, thanks!
