### ISSUE TITLE
Is cargo tree support workspace ?

### ISSUE THREAD

**Issue by Pana** [sfackler/cargo-tree#73]

**Comment by Boscop** [comment]
Yes, please add support for workspaces. So that `-d` can be used to find out which crates in your workspace use different versions of the same dep.

**Comment by luser** [comment]
@sfackler I assume #86 made some foundational changes to support this, but it looks like in practice you still need to specify a single package to print a tree of? `cargo metadata` supports being run from a workspace so presumably `cargo tree` could support that usecase as well.
