### ISSUE TITLE
Turn into library

### ISSUE THREAD

**Issue by dpc** [sfackler/cargo-tree#76]
For `cargo-crev` I'd like to perform recursive dependency analysis - eg. to count total numbers of lines of code that a given dependency adds to the project (including its dependencies, recursively).

I've decided to take a look at `cargo-tree`, since it's doing what I'll have to do. And turns out, I could just copy&paste most of `main.rs` verbatim and it will probably work for me. But that seems... meh. So I wonder - could we split this project into `lib.rs` and `main.rs`, making all the resolution and options bits reusable, and keeping only formatting in the binary? This way any project that needs to go through a graph of dependencies, could benefit?

**Comment by sfackler** [comment]
cargo-tree is going to become a pretty small wrapper over cargo-metadata in the next release or two, so I'm not sure how much splitting out a library would help at that point.

**Comment by dpc** [comment]
I don't understand the details here. `cargo-metadata` is like a command? Will it have an underlying library / by part of `cargo` library?

**Comment by sfackler** [comment]
`cargo-metadata` is part of cargo itself.

```
cargo-metadata 
Output the resolved dependencies of a package, the concrete used versions including overrides, in machine-readable
format

USAGE:
    cargo metadata [OPTIONS]

OPTIONS:
    -q, --quiet                       No output printed to stdout
        --features <FEATURES>         Space-separated list of features to activate
        --all-features                Activate all available features
        --no-default-features         Do not activate the `default` feature
        --no-deps                     Output information only about the root package and don't fetch dependencies
        --manifest-path <PATH>        Path to Cargo.toml
        --format-version <VERSION>    Format version [possible values: 1]
    -v, --verbose                     Use verbose output (-vv very verbose/build.rs output)
        --color <WHEN>                Coloring: auto, always, never
        --frozen                      Require Cargo.lock and cache are up to date
        --locked                      Require Cargo.lock is up to date
        --offline                     Run without accessing the network
    -Z <FLAG>...                      Unstable (nightly-only) flags to Cargo, see 'cargo -Z help' for details
    -h, --help                        Prints help information
```

**Comment by dpc** [comment]
But is there a library (/library call) that I can do to get a resolved to a graph of deps, like in `main.rs` of `cargo-tree`?

**Comment by sfackler** [comment]
That is basically what cargo-metadata gives you.

**Comment by dpc** [comment]
But `cargo-metadata` isn't a library. :D . I don't want to run commands. :rofl:

**Comment by ehuss** [comment]
There is the [`cargo_metadata`](https://crates.io/crates/cargo_metadata) library to assist fetching the metadata, which is the preferred way to interact with cargo.

**Comment by dpc** [comment]
But this ... calls `cargo metadata` and deserializes its output? Why no love for libraries? Code in `main.rs` of `cargo-tree` is perfect - sleek and efficient, minimal. :)

I guess I can just copy current `main.rs` and maintain that as a crate if there's no plan to do so. I just wanted to make sure I'm not going to be duplicating the effort.
