### ISSUE TITLE
url-0.5.9: could not parse input as TOML

### ISSUE THREAD

**Issue by matthewkmayer** [sfackler/cargo-tree#8]
As seen in [rusoto](https://github.com/rusoto/rusoto) at `76c7c56`, where we're still using an old version of `url`, `0.5.9`:

`$ cargo tree` gives

``` bash
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/url-0.5.9/Cargo.toml`

Caused by:
  could not parse input as TOML
/Users/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/url-0.5.9/Cargo.toml:14:3 expected a newline after table definition

error: 
```

Line in file specified:

``` toml
[[test]] name = "format"
```

Updating `url` to the latest version, `1.1.1`, allows `cargo tree` to work as expected.  Is this a bug in pre-1.0.0 `url` or `cargo-tree`?

**Comment by sfackler** [comment]
That's a bug in pre-1.0.0 url, I believe due to a fix in the toml crate to stop parsing invalid syntax: https://github.com/alexcrichton/toml-rs/pull/94

**Comment by matthewkmayer** [comment]
Thanks, sounds like this issue is invalid and should be closed. 😄
