### ISSUE TITLE
no color

### ISSUE THREAD

**Issue by bestouff** [sfackler/cargo-tree#89]
Hi,

even with `--color always`, the output is still monochrome (v0.28.0).

**Comment by sfackler** [comment]
What color are you expecting?

**Comment by bestouff** [comment]
I don't know. There's a `--color` option, I find color to always help, I thought the option would add some colors to the output.

**Comment by sfackler** [comment]
That option is forwarded to cargo for use with its own output.

**Comment by bestouff** [comment]
This is not obvious for the end-user. But ok, I get it's not that interesting.
